### ISSUE TITLE
bug(): Tapestries crash on errors

### ISSUE THREAD

**Issue by jaumard** [fabrix-app/spool-express#16]
#### Issue Description
Look like boom is not where is suppose to be :) 
```
Unhandled rejection TypeError: res.boom.wrap is not a function
    at response.then.catch.error (/Users/jaumard/IdeaProjects/lisa-server/node_modules/@fabrix/spool-express/dist/api/controllers/TapestryController.js:56:47)
    at tryCatcher (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jaumard/IdeaProjects/lisa-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

```

#### Environment
- node version: 10
- fabrix version: 1.6
- operating system: mac

**Comment by scott-wyatt** [comment]
I know this is super old, but I'm going to replace express-boom with Hapi Boom, since the express is completely deprecated. #
